### ISSUE TITLE
List Resource button doesn't redirect to correct page

### ISSUE THREAD

**Issue by gerzarko** [datagrove/marketplace-us#113] opened 2024-08-07 16:40 UTC
Describe the bug
The button "List Resource" on the the page creator profile doesn't link to the list resource page, instead it reloads the page and stays in the creator profile

To Reproduce
1. Go to creatorProfile
2. Click on on the button "List Resource"
3. Wait for redirect
4. It reloads the page

Expected behavior
Redirect to the List Resource Page

Screenshots

Additional context

Proposed Solution
Change tag to redirect to List Resource Page

- [ ] I am willing to submit a pull request for this issue.

**Comment by r-southworth** [comment] 2024-08-09 18:07
Closing as duplicate of https://github.com/datagrove/marketplace-us/issues/105

**Closed by r-southworth** 2024-08-09 18:07 UTC
Labels: bug
